//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tours1Entities2 : DbContext
    {
        private static Tours1Entities2 _context;
        public Tours1Entities2()
            : base("name=Tours1Entities2")
        {
        }

        public static Tours1Entities2 GetContext()
        {
            if (_context == null)
                _context = new Tours1Entities2();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<HotelComment> HotelComment { get; set; }
        public virtual DbSet<Hotelmage> Hotelmage { get; set; }
        public virtual DbSet<HotelOfTour> HotelOfTour { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Tours> Tours { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
